
---
 ############################################
 # These settings are generated server-side #
 # and should not be manually changed.      #
 # ##########################################
 # Username to authenticate.
 username: duane
 # authType => 'pass' for password authentication or 'key' for key-based authentication.
 authType: pass
 # Remote SSH server.
 # ex:  10.1.1.1
 # ex: www.example.com
 hostname:  X.X.X.X
 # SSH port number
 hostport: 22
 # Currently, only 'totp' is supported.
 type2fa: totp
